# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 434, 533, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_childnavigation = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.layout_childnavigation.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.layout_childnavigation.setContentsMargins(11, 11, 11, 11)
        self.layout_childnavigation.setSpacing(10)
        self.layout_childnavigation.setObjectName("layout_childnavigation")
        self.btn_automation = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_automation.sizePolicy().hasHeightForWidth())
        self.btn_automation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_automation.setFont(font)
        self.btn_automation.setObjectName("btn_automation")
        self.layout_childnavigation.addWidget(self.btn_automation)
        self.btn_logging = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logging.sizePolicy().hasHeightForWidth())
        self.btn_logging.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logging.setFont(font)
        self.btn_logging.setObjectName("btn_logging")
        self.layout_childnavigation.addWidget(self.btn_logging)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 8, 781, 113))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.layout_tempsensors = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.layout_tempsensors.setContentsMargins(11, 11, 11, 11)
        self.layout_tempsensors.setSpacing(10)
        self.layout_tempsensors.setObjectName("layout_tempsensors")
        self.layout_temp1 = QtWidgets.QFrame(self.layoutWidget1)
        self.layout_temp1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.layout_temp1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.layout_temp1.setLineWidth(1)
        self.layout_temp1.setObjectName("layout_temp1")
        self.lcd_temp1 = QtWidgets.QLCDNumber(self.layout_temp1)
        self.lcd_temp1.setGeometry(QtCore.QRect(6, 40, 133, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcd_temp1.setFont(font)
        self.lcd_temp1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcd_temp1.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd_temp1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd_temp1.setSmallDecimalPoint(False)
        self.lcd_temp1.setDigitCount(5)
        self.lcd_temp1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_temp1.setProperty("value", 24.0)
        self.lcd_temp1.setProperty("intValue", 24)
        self.lcd_temp1.setObjectName("lcd_temp1")
        self.lbl_temp1 = QtWidgets.QLabel(self.layout_temp1)
        self.lbl_temp1.setGeometry(QtCore.QRect(10, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_temp1.setFont(font)
        self.lbl_temp1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_temp1.setObjectName("lbl_temp1")
        self.layout_tempsensors.addWidget(self.layout_temp1)
        self.layout_temp2 = QtWidgets.QFrame(self.layoutWidget1)
        self.layout_temp2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.layout_temp2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.layout_temp2.setLineWidth(1)
        self.layout_temp2.setObjectName("layout_temp2")
        self.lcd_temp2 = QtWidgets.QLCDNumber(self.layout_temp2)
        self.lcd_temp2.setGeometry(QtCore.QRect(10, 40, 129, 61))
        self.lcd_temp2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcd_temp2.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd_temp2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd_temp2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_temp2.setObjectName("lcd_temp2")
        self.lbl_temp2 = QtWidgets.QLabel(self.layout_temp2)
        self.lbl_temp2.setGeometry(QtCore.QRect(10, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_temp2.setFont(font)
        self.lbl_temp2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_temp2.setObjectName("lbl_temp2")
        self.layout_tempsensors.addWidget(self.layout_temp2)
        self.layout_temp3 = QtWidgets.QFrame(self.layoutWidget1)
        self.layout_temp3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.layout_temp3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.layout_temp3.setLineWidth(1)
        self.layout_temp3.setObjectName("layout_temp3")
        self.lcd_temp3 = QtWidgets.QLCDNumber(self.layout_temp3)
        self.lcd_temp3.setGeometry(QtCore.QRect(10, 40, 125, 61))
        self.lcd_temp3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcd_temp3.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd_temp3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd_temp3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_temp3.setObjectName("lcd_temp3")
        self.lbl_temp3 = QtWidgets.QLabel(self.layout_temp3)
        self.lbl_temp3.setGeometry(QtCore.QRect(10, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_temp3.setFont(font)
        self.lbl_temp3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_temp3.setObjectName("lbl_temp3")
        self.layout_tempsensors.addWidget(self.layout_temp3)
        self.layout_temp4 = QtWidgets.QFrame(self.layoutWidget1)
        self.layout_temp4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.layout_temp4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.layout_temp4.setLineWidth(1)
        self.layout_temp4.setObjectName("layout_temp4")
        self.lcd_temp4 = QtWidgets.QLCDNumber(self.layout_temp4)
        self.lcd_temp4.setGeometry(QtCore.QRect(10, 40, 125, 61))
        self.lcd_temp4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcd_temp4.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd_temp4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd_temp4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_temp4.setObjectName("lcd_temp4")
        self.lbl_temp4 = QtWidgets.QLabel(self.layout_temp4)
        self.lbl_temp4.setGeometry(QtCore.QRect(10, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_temp4.setFont(font)
        self.lbl_temp4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_temp4.setObjectName("lbl_temp4")
        self.layout_tempsensors.addWidget(self.layout_temp4)
        self.layout_temp5 = QtWidgets.QFrame(self.layoutWidget1)
        self.layout_temp5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.layout_temp5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.layout_temp5.setLineWidth(1)
        self.layout_temp5.setObjectName("layout_temp5")
        self.lcd_temp5 = QtWidgets.QLCDNumber(self.layout_temp5)
        self.lcd_temp5.setGeometry(QtCore.QRect(10, 40, 129, 61))
        self.lcd_temp5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcd_temp5.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd_temp5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd_temp5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_temp5.setObjectName("lcd_temp5")
        self.lbl_temp5 = QtWidgets.QLabel(self.layout_temp5)
        self.lbl_temp5.setGeometry(QtCore.QRect(10, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_temp5.setFont(font)
        self.lbl_temp5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_temp5.setObjectName("lbl_temp5")
        self.layout_tempsensors.addWidget(self.layout_temp5)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(568, 152, 225, 233))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.layout_relaycontrol = QtWidgets.QGridLayout(self.layoutWidget2)
        self.layout_relaycontrol.setContentsMargins(11, 11, 11, 11)
        self.layout_relaycontrol.setSpacing(6)
        self.layout_relaycontrol.setObjectName("layout_relaycontrol")
        self.btn_relay1_on = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_relay1_on.sizePolicy().hasHeightForWidth())
        self.btn_relay1_on.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_relay1_on.setFont(font)
        self.btn_relay1_on.setStyleSheet("")
        self.btn_relay1_on.setIconSize(QtCore.QSize(14, 14))
        self.btn_relay1_on.setObjectName("btn_relay1_on")
        self.layout_relaycontrol.addWidget(self.btn_relay1_on, 0, 0, 1, 1)
        self.btn_relay2_on = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_relay2_on.sizePolicy().hasHeightForWidth())
        self.btn_relay2_on.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_relay2_on.setFont(font)
        self.btn_relay2_on.setStyleSheet("")
        self.btn_relay2_on.setObjectName("btn_relay2_on")
        self.layout_relaycontrol.addWidget(self.btn_relay2_on, 0, 1, 1, 1)
        self.btn_relay1_off = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_relay1_off.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_relay1_off.sizePolicy().hasHeightForWidth())
        self.btn_relay1_off.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_relay1_off.setFont(font)
        self.btn_relay1_off.setStyleSheet("")
        self.btn_relay1_off.setObjectName("btn_relay1_off")
        self.layout_relaycontrol.addWidget(self.btn_relay1_off, 1, 0, 1, 1)
        self.btn_relay2_off = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_relay2_off.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_relay2_off.sizePolicy().hasHeightForWidth())
        self.btn_relay2_off.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_relay2_off.setFont(font)
        self.btn_relay2_off.setStyleSheet("")
        self.btn_relay2_off.setObjectName("btn_relay2_off")
        self.layout_relaycontrol.addWidget(self.btn_relay2_off, 1, 1, 1, 1)
        self.btn_configuration = QtWidgets.QPushButton(self.centralWidget)
        self.btn_configuration.setGeometry(QtCore.QRect(608, 400, 145, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_configuration.setFont(font)
        self.btn_configuration.setObjectName("btn_configuration")
        self.child_navigator = QtWidgets.QStackedWidget(self.centralWidget)
        self.child_navigator.setGeometry(QtCore.QRect(12, 128, 550, 302))
        self.child_navigator.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.child_navigator.setAutoFillBackground(False)
        self.child_navigator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.child_navigator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.child_navigator.setLineWidth(1)
        self.child_navigator.setObjectName("child_navigator")
        self.child_automation = QtWidgets.QWidget()
        self.child_automation.setObjectName("child_automation")
        self.relay2_frame = QtWidgets.QFrame(self.child_automation)
        self.relay2_frame.setGeometry(QtCore.QRect(276, 4, 269, 293))
        self.relay2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.relay2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.relay2_frame.setObjectName("relay2_frame")
        self.layoutWidget_8 = QtWidgets.QWidget(self.relay2_frame)
        self.layoutWidget_8.setGeometry(QtCore.QRect(4, 84, 261, 101))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.relay2_layout_maxtemp = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.relay2_layout_maxtemp.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.relay2_layout_maxtemp.setContentsMargins(11, 11, 11, 11)
        self.relay2_layout_maxtemp.setSpacing(2)
        self.relay2_layout_maxtemp.setObjectName("relay2_layout_maxtemp")
        self.relay2_label_maxtemp = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.relay2_label_maxtemp.setFont(font)
        self.relay2_label_maxtemp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.relay2_label_maxtemp.setAutoFillBackground(True)
        self.relay2_label_maxtemp.setAlignment(QtCore.Qt.AlignCenter)
        self.relay2_label_maxtemp.setObjectName("relay2_label_maxtemp")
        self.relay2_layout_maxtemp.addWidget(self.relay2_label_maxtemp)
        self.relay2_spinbox_maxtemp = QtWidgets.QDoubleSpinBox(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.relay2_spinbox_maxtemp.sizePolicy().hasHeightForWidth())
        self.relay2_spinbox_maxtemp.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 255, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 230, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 137, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 230, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 255, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 230, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 137, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 230, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 255, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 230, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 137, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.relay2_spinbox_maxtemp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.relay2_spinbox_maxtemp.setFont(font)
        self.relay2_spinbox_maxtemp.setToolTipDuration(-1)
        self.relay2_spinbox_maxtemp.setStyleSheet("QDoubleSpinBox { border: 1px inset grey; } \n"
"QDoubleSpinBox::up-button { subcontrol-position: right; width: 70px; height: 65px;}\n"
"QDoubleSpinBox::down-button { subcontrol-position: left; width: 70px; height: 65px;}")
        self.relay2_spinbox_maxtemp.setWrapping(False)
        self.relay2_spinbox_maxtemp.setFrame(True)
        self.relay2_spinbox_maxtemp.setAlignment(QtCore.Qt.AlignCenter)
        self.relay2_spinbox_maxtemp.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.relay2_spinbox_maxtemp.setSpecialValueText("")
        self.relay2_spinbox_maxtemp.setAccelerated(False)
        self.relay2_spinbox_maxtemp.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.relay2_spinbox_maxtemp.setKeyboardTracking(True)
        self.relay2_spinbox_maxtemp.setSingleStep(0.5)
        self.relay2_spinbox_maxtemp.setProperty("value", 20.0)
        self.relay2_spinbox_maxtemp.setObjectName("relay2_spinbox_maxtemp")
        self.relay2_layout_maxtemp.addWidget(self.relay2_spinbox_maxtemp)
        self.layoutWidget_9 = QtWidgets.QWidget(self.relay2_frame)
        self.layoutWidget_9.setGeometry(QtCore.QRect(24, 4, 221, 79))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.relay2_layout_sensorselector = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.relay2_layout_sensorselector.setContentsMargins(11, 11, 11, 11)
        self.relay2_layout_sensorselector.setSpacing(2)
        self.relay2_layout_sensorselector.setObjectName("relay2_layout_sensorselector")
        self.relay2_label_relay2 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.relay2_label_relay2.setFont(font)
        self.relay2_label_relay2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.relay2_label_relay2.setAutoFillBackground(True)
        self.relay2_label_relay2.setAlignment(QtCore.Qt.AlignCenter)
        self.relay2_label_relay2.setObjectName("relay2_label_relay2")
        self.relay2_layout_sensorselector.addWidget(self.relay2_label_relay2)
        self.relay2_combobox_sensors = QtWidgets.QComboBox(self.layoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relay2_combobox_sensors.sizePolicy().hasHeightForWidth())
        self.relay2_combobox_sensors.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.relay2_combobox_sensors.setFont(font)
        self.relay2_combobox_sensors.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.relay2_combobox_sensors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.relay2_combobox_sensors.setAutoFillBackground(True)
        self.relay2_combobox_sensors.setIconSize(QtCore.QSize(32, 32))
        self.relay2_combobox_sensors.setObjectName("relay2_combobox_sensors")
        self.relay2_combobox_sensors.addItem("")
        self.relay2_combobox_sensors.addItem("")
        self.relay2_combobox_sensors.addItem("")
        self.relay2_combobox_sensors.addItem("")
        self.relay2_combobox_sensors.addItem("")
        self.relay2_layout_sensorselector.addWidget(self.relay2_combobox_sensors)
        self.layoutWidget_10 = QtWidgets.QWidget(self.relay2_frame)
        self.layoutWidget_10.setGeometry(QtCore.QRect(4, 188, 261, 101))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.relay2_layout_mintemp = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.relay2_layout_mintemp.setContentsMargins(11, 11, 11, 11)
        self.relay2_layout_mintemp.setSpacing(2)
        self.relay2_layout_mintemp.setObjectName("relay2_layout_mintemp")
        self.relay2_label_mintemp = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.relay2_label_mintemp.setFont(font)
        self.relay2_label_mintemp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.relay2_label_mintemp.setAutoFillBackground(True)
        self.relay2_label_mintemp.setAlignment(QtCore.Qt.AlignCenter)
        self.relay2_label_mintemp.setObjectName("relay2_label_mintemp")
        self.relay2_layout_mintemp.addWidget(self.relay2_label_mintemp)
        self.relay2_spinbox_mintemp = QtWidgets.QDoubleSpinBox(self.layoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.relay2_spinbox_mintemp.sizePolicy().hasHeightForWidth())
        self.relay2_spinbox_mintemp.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 105, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 48, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 163, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 105, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 48, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 163, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 105, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 48, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.relay2_spinbox_mintemp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.relay2_spinbox_mintemp.setFont(font)
        self.relay2_spinbox_mintemp.setToolTipDuration(-1)
        self.relay2_spinbox_mintemp.setStyleSheet("QDoubleSpinBox { border: 1px inset grey; } \n"
"QDoubleSpinBox::up-button { subcontrol-position: right; width: 70px; height: 65px;}\n"
"QDoubleSpinBox::down-button { subcontrol-position: left; width: 70px; height: 65px;}")
        self.relay2_spinbox_mintemp.setWrapping(False)
        self.relay2_spinbox_mintemp.setFrame(True)
        self.relay2_spinbox_mintemp.setAlignment(QtCore.Qt.AlignCenter)
        self.relay2_spinbox_mintemp.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.relay2_spinbox_mintemp.setSpecialValueText("")
        self.relay2_spinbox_mintemp.setAccelerated(False)
        self.relay2_spinbox_mintemp.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.relay2_spinbox_mintemp.setKeyboardTracking(True)
        self.relay2_spinbox_mintemp.setMinimum(-30.0)
        self.relay2_spinbox_mintemp.setSingleStep(0.5)
        self.relay2_spinbox_mintemp.setProperty("value", 0.0)
        self.relay2_spinbox_mintemp.setObjectName("relay2_spinbox_mintemp")
        self.relay2_layout_mintemp.addWidget(self.relay2_spinbox_mintemp)
        self.relay1_frame = QtWidgets.QFrame(self.child_automation)
        self.relay1_frame.setGeometry(QtCore.QRect(4, 4, 269, 293))
        self.relay1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.relay1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.relay1_frame.setLineWidth(5)
        self.relay1_frame.setObjectName("relay1_frame")
        self.layoutWidget_2 = QtWidgets.QWidget(self.relay1_frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(4, 84, 261, 101))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.relay1_layout_maxtemp = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.relay1_layout_maxtemp.setContentsMargins(11, 11, 11, 11)
        self.relay1_layout_maxtemp.setSpacing(2)
        self.relay1_layout_maxtemp.setObjectName("relay1_layout_maxtemp")
        self.relay1_label_maxtemp = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.relay1_label_maxtemp.setFont(font)
        self.relay1_label_maxtemp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.relay1_label_maxtemp.setAutoFillBackground(True)
        self.relay1_label_maxtemp.setAlignment(QtCore.Qt.AlignCenter)
        self.relay1_label_maxtemp.setObjectName("relay1_label_maxtemp")
        self.relay1_layout_maxtemp.addWidget(self.relay1_label_maxtemp)
        self.relay1_spinbox_maxtemp = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.relay1_spinbox_maxtemp.sizePolicy().hasHeightForWidth())
        self.relay1_spinbox_maxtemp.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 255, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 230, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 137, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 230, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 255, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 230, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 137, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 230, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 255, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 230, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 137, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 103, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 206, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.relay1_spinbox_maxtemp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.relay1_spinbox_maxtemp.setFont(font)
        self.relay1_spinbox_maxtemp.setToolTipDuration(-1)
        self.relay1_spinbox_maxtemp.setStyleSheet("QDoubleSpinBox { border: 1px inset grey; } \n"
"QDoubleSpinBox::up-button { subcontrol-position: right; width: 70px; height: 65px;}\n"
"QDoubleSpinBox::down-button { subcontrol-position: left; width: 70px; height: 65px;}")
        self.relay1_spinbox_maxtemp.setWrapping(False)
        self.relay1_spinbox_maxtemp.setFrame(True)
        self.relay1_spinbox_maxtemp.setAlignment(QtCore.Qt.AlignCenter)
        self.relay1_spinbox_maxtemp.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.relay1_spinbox_maxtemp.setSpecialValueText("")
        self.relay1_spinbox_maxtemp.setAccelerated(False)
        self.relay1_spinbox_maxtemp.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.relay1_spinbox_maxtemp.setKeyboardTracking(True)
        self.relay1_spinbox_maxtemp.setSingleStep(0.5)
        self.relay1_spinbox_maxtemp.setProperty("value", 20.0)
        self.relay1_spinbox_maxtemp.setObjectName("relay1_spinbox_maxtemp")
        self.relay1_layout_maxtemp.addWidget(self.relay1_spinbox_maxtemp)
        self.layoutWidget_3 = QtWidgets.QWidget(self.relay1_frame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(24, 4, 221, 79))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.relay1_layout_sensorselector = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.relay1_layout_sensorselector.setContentsMargins(11, 11, 11, 11)
        self.relay1_layout_sensorselector.setSpacing(2)
        self.relay1_layout_sensorselector.setObjectName("relay1_layout_sensorselector")
        self.relay1_label_relay1 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.relay1_label_relay1.setFont(font)
        self.relay1_label_relay1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.relay1_label_relay1.setAutoFillBackground(True)
        self.relay1_label_relay1.setAlignment(QtCore.Qt.AlignCenter)
        self.relay1_label_relay1.setObjectName("relay1_label_relay1")
        self.relay1_layout_sensorselector.addWidget(self.relay1_label_relay1)
        self.relay1_combobox_sensors = QtWidgets.QComboBox(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relay1_combobox_sensors.sizePolicy().hasHeightForWidth())
        self.relay1_combobox_sensors.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.relay1_combobox_sensors.setFont(font)
        self.relay1_combobox_sensors.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.relay1_combobox_sensors.setIconSize(QtCore.QSize(16, 16))
        self.relay1_combobox_sensors.setObjectName("relay1_combobox_sensors")
        self.relay1_combobox_sensors.addItem("")
        self.relay1_combobox_sensors.addItem("")
        self.relay1_combobox_sensors.addItem("")
        self.relay1_combobox_sensors.addItem("")
        self.relay1_combobox_sensors.addItem("")
        self.relay1_layout_sensorselector.addWidget(self.relay1_combobox_sensors)
        self.layoutWidget_4 = QtWidgets.QWidget(self.relay1_frame)
        self.layoutWidget_4.setGeometry(QtCore.QRect(4, 188, 261, 101))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.relay1_layout_mintemp = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.relay1_layout_mintemp.setContentsMargins(11, 11, 11, 11)
        self.relay1_layout_mintemp.setSpacing(2)
        self.relay1_layout_mintemp.setObjectName("relay1_layout_mintemp")
        self.relay1_label_mintemp = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.relay1_label_mintemp.setFont(font)
        self.relay1_label_mintemp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.relay1_label_mintemp.setAutoFillBackground(True)
        self.relay1_label_mintemp.setAlignment(QtCore.Qt.AlignCenter)
        self.relay1_label_mintemp.setObjectName("relay1_label_mintemp")
        self.relay1_layout_mintemp.addWidget(self.relay1_label_mintemp)
        self.relay1_spinbox_mintemp = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.relay1_spinbox_mintemp.sizePolicy().hasHeightForWidth())
        self.relay1_spinbox_mintemp.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 105, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 48, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 163, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 105, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 48, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 163, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 105, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 48, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(103, 36, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 72, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.relay1_spinbox_mintemp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.relay1_spinbox_mintemp.setFont(font)
        self.relay1_spinbox_mintemp.setToolTipDuration(-1)
        self.relay1_spinbox_mintemp.setStyleSheet("QDoubleSpinBox { border: 1px inset grey; } \n"
"QDoubleSpinBox::up-button { subcontrol-position: right; width: 70px; height: 65px;}\n"
"QDoubleSpinBox::down-button { subcontrol-position: left; width: 70px; height: 65px;}")
        self.relay1_spinbox_mintemp.setWrapping(False)
        self.relay1_spinbox_mintemp.setFrame(True)
        self.relay1_spinbox_mintemp.setAlignment(QtCore.Qt.AlignCenter)
        self.relay1_spinbox_mintemp.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.relay1_spinbox_mintemp.setSpecialValueText("")
        self.relay1_spinbox_mintemp.setAccelerated(False)
        self.relay1_spinbox_mintemp.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.relay1_spinbox_mintemp.setKeyboardTracking(True)
        self.relay1_spinbox_mintemp.setMinimum(-30.0)
        self.relay1_spinbox_mintemp.setSingleStep(0.5)
        self.relay1_spinbox_mintemp.setProperty("value", 0.0)
        self.relay1_spinbox_mintemp.setObjectName("relay1_spinbox_mintemp")
        self.relay1_layout_mintemp.addWidget(self.relay1_spinbox_mintemp)
        self.child_navigator.addWidget(self.child_automation)
        self.child_logging = QtWidgets.QWidget()
        self.child_logging.setObjectName("child_logging")
        self.child_navigator.addWidget(self.child_logging)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.child_navigator.setCurrentIndex(0)
        self.relay2_combobox_sensors.setCurrentIndex(0)
        self.relay1_combobox_sensors.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_automation.setText(_translate("MainWindow", "Automation"))
        self.btn_logging.setText(_translate("MainWindow", "Logging"))
        self.lbl_temp1.setText(_translate("MainWindow", "Temp 1"))
        self.lbl_temp2.setText(_translate("MainWindow", "Temp 2"))
        self.lbl_temp3.setText(_translate("MainWindow", "Temp 3"))
        self.lbl_temp4.setText(_translate("MainWindow", "Temp 4"))
        self.lbl_temp5.setText(_translate("MainWindow", "Temp 5"))
        self.btn_relay1_on.setText(_translate("MainWindow", "Relay 1\n"
"Activate"))
        self.btn_relay2_on.setText(_translate("MainWindow", "Relay 2\n"
"Activate"))
        self.btn_relay1_off.setText(_translate("MainWindow", "Relay 1\n"
"Deactivate"))
        self.btn_relay2_off.setText(_translate("MainWindow", "Relay 2\n"
"Deactivate"))
        self.btn_configuration.setText(_translate("MainWindow", "Configuration"))
        self.relay2_label_maxtemp.setText(_translate("MainWindow", "Maximum Temp"))
        self.relay2_label_relay2.setText(_translate("MainWindow", "Relay 2"))
        self.relay2_combobox_sensors.setItemText(0, _translate("MainWindow", "temp_1"))
        self.relay2_combobox_sensors.setItemText(1, _translate("MainWindow", "temp_2"))
        self.relay2_combobox_sensors.setItemText(2, _translate("MainWindow", "temp_3"))
        self.relay2_combobox_sensors.setItemText(3, _translate("MainWindow", "temp_4"))
        self.relay2_combobox_sensors.setItemText(4, _translate("MainWindow", "temp_5"))
        self.relay2_label_mintemp.setText(_translate("MainWindow", "Minimum Temp"))
        self.relay1_label_maxtemp.setText(_translate("MainWindow", "Maximum Temp"))
        self.relay1_label_relay1.setText(_translate("MainWindow", "Relay 1"))
        self.relay1_combobox_sensors.setItemText(0, _translate("MainWindow", "temp_1"))
        self.relay1_combobox_sensors.setItemText(1, _translate("MainWindow", "temp_2"))
        self.relay1_combobox_sensors.setItemText(2, _translate("MainWindow", "temp_3"))
        self.relay1_combobox_sensors.setItemText(3, _translate("MainWindow", "temp_4"))
        self.relay1_combobox_sensors.setItemText(4, _translate("MainWindow", "temp_5"))
        self.relay1_label_mintemp.setText(_translate("MainWindow", "Minimum Temp"))

